name=tiny FOC
version=1.0.0
author=Julius Schneider
maintainer=Julius Schneider <mail@example.com>
sentence=An optimized C-Port of SimpleFOC
paragraph=C library intended for hobby comunity to run the BLDC and Stepper motor using FOC algorithm.
category=Device Control
url=https://example.com
architectures=*
includes=tinyFOC.h
